#!/usr/bin/env bash
export PORTABLE="$HOME/.portable"
#export PORTABLE="$(cd -- "$(dirname "$0")" > /dev/null 2>&1; pwd -P)"

prepend_to_path() {
  PATH=":$PATH"
  PATH="$1${PATH//$1:/}"
}

prepend_to_path "$PORTABLE/bin"
prepend_to_path "$PORTABLE/scripts"

source_file() {
  [ -f "$1" ] && source "$1"
}

source_file "$PORTABLE/.profile"
source_file "$PORTABLE/.bashrc"
source_file "$PORTABLE/.bash_aliases"

source_file "$HOME/.fzf/shell/key-bindings.bash"
