#!/usr/bin/env bash
cd "${0%/*}/.."
source './scripts/utils.bash'
if [ ! "$(which tmux)" ]; then
  error_msg 'tmux not found, run "get-tmux"'
  exit 1
fi
exec tmux -f "$PWD/.tmux.conf" -L portable $@
